email: clubbadguenange@gmail.com
title: Le Badminton Guénangeois
description: >- 
  Le LBG est le principal club de badminton de la ville de Guénange et ses environs (Bertrange, Illange, Bousse, Volstroff, Metzervisse et Ay-sur-Moselle).
  Nous accueillons les badistes principalement pour du loisir mais aussi de la compétition.
baseurl: "" # le sous-chemin de votre site, par exemple /blog
url: "" # le nom d'hôte et le protocole de base de votre site, par exemple http://example.com

# Paramètres de construction
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
navigation:
  - title: Accueil
    url: /
  - title: À propos
    url: /a-propos/
  - title: Événements
    url: /evenements/
  - title: Adhésion
    url: /adhesion/
  - title: Galerie
    url: /galerie/
  - title: Contact
    url: /contact/

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

# Réseaux sociaux
social:
  facebook: https://fb.me/lbg57
  instagram: https://instagram.com/lebadmintonguenangeois

# Informations de contact
contact:
  address: 1, rue Mozart, 57310 Guénange
  phone: 0767972461
  email: clubbadguenange@gmail.com

# Exclusions du traitement
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github